function [timestamps] = read_in_timestamps(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Based on script auto-generated by MATLAB on 2017/11/06 16:36:24

%% Import neural mapper frame-grab information

formatSpec = '%12s%[^\n\r]';
fileID = fopen(filename,'r');

dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false);
dataArray{1} = strtrim(dataArray{1});

fclose(fileID);
NeuViewtime = dataArray{:, 1};
cell_array_tmsp = NeuViewtime(6:end);

clearvars filename formatSpec fileID dataArray ans;

%% put timestamps into a single array

timestamps = zeros(size(cell_array_tmsp,1),1);
for stamp = 1:length(cell_array_tmsp)
    thisStamp = cell_array_tmsp{stamp};
    numbahz = regexp(thisStamp,'\d');
    secondNumber_ind = find(diff(numbahz)>1)+2;
    timestamps(stamp) = str2double(thisStamp(secondNumber_ind:end));
end

end